spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: "localhost:9300"

keyword-search.allowed-pattern: "[^*?]+"

---
spring:
  profiles: docker
  data:
    elasticsearch:
      cluster-nodes: "elasticsearch:9300"
